ChainID = 1122
CoinPrecision = 100000000
CoinSymbol = "Rayaxe"
Title="chain"
TestNet = true
FixTime=false
version="1.65.2-0670237"
# 是否按照块高度设置过期时间，开启后优化了交易去重性能

[crypto]
[crypto.sub.secp256k1eth]
evmChainID = 1122

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "info"
logConsoleLevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false

[blockchain]
defCacheSize=128
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
dbCache=64
isStrongConsistency=false
singleMode=true
batchsync=false
isRecordBlockSequence=true
isParaChain=false
enableTxQuickIndex=true
enableReExecLocal=true
# 使能精简localdb
enableReduceLocaldb=true
enablePushSubscribe=false
# 关闭分片存储,默认false为开启分片存储;平行链不需要分片需要修改此默认参数为true
disableShard=false
# 分片存储中每个大块包含的区块数
chunkblockNum=100
# 使能从P2pStore中获取数据
enableFetchP2pstore=true
# 使能假设已删除已归档数据后,获取数据情况
enableIfDelLocalChunk=false
# 使能保存block kvs
enableSaveBlockKVs=true

[p2p]
# p2p类型
types=["dht"]
# 是否启动P2P服务
enable=true
# 使用的数据库类型
driver="leveldb"
# 使用的数据库类型
dbPath="datadir/addrbook"
# 数据库缓存大小
dbCache=4
# GRPC请求日志文件
grpcLogFile="grpc33.log"
#waitPid 等待seed导入
waitPid=false


[p2p.sub.gossip]
seeds=[]
isSeed=false
serverStart=true
innerSeedEnable=true
useGithub=true
innerBounds=300
#是否启用ssl/tls 通信，默认不开启
enableTLS=false
#如果需要CA配合认证，则需要配置caCert,caServer
caCert=""
certFile=""
keyFile=""
# ca服务端接口http://ip:port
caServer=""

[p2p.sub.dht]
seeds=[]
port=13803
maxConnectNum=100
# 禁止通过局域网发现节点
disableFindLANPeers=false
# 配置为全节点模式，全节点保存所有分片数据
isFullNode=false
# 分片数据默认保存比例，最低可配置为10
percentage=30

[rpc]
jrpcBindAddr=":8801"
grpcBindAddr=":8802"
whitelist=["127.0.0.1"]
jrpcFuncWhitelist=["*"]
grpcFuncWhitelist=["*"]

[rpc.sub.eth]
enable=true
httpAddr=":8545"
httpApi=["eth","web3","personal","admin","net"]
# websocket 绑定地址
wsAddr=":8546"
wsApi=["eth","web3","personal","admin","net"]

[address]
#旧的版本或bty缺省是btc格式地址，可以支持eth格式地址，如果对地址格式没要求，采用缺省配置即可
defaultDriver="eth"
[address.enableHeight]
eth=0

[mempool]
name="price"
poolCacheSize=10240
maxTxNumPerAccount=100
# 最小得交易手续费率，这个没有默认值，必填，一般是0.001 coins
minTxFeeRate=100000
# 最大的交易手续费率, 0.1 coins
maxTxFeeRate=10000000
# 单笔交易最大的手续费, 10 coins
maxTxFee=100000000
isLevelFee=true
enableEthCheck=true

[mempool.sub.timeline]
poolCacheSize=10240

[mempool.sub.score]
poolCacheSize=10240
timeParam=1      #时间占价格比例
priceConstant=10  #手续费相对于时间的一个的常量,排队时手续费高1e3的分数~=快1h的分数
pricePower=1     #常量比例

[mempool.sub.price]
poolCacheSize=10240

[consensus]
name="solo"
minerstart=true

# ###########privatekey:73e66f099144f820753aa3a5e131785b528081da572e16339fcd02de05de719e
# ###########pubkey: 0xab7F5238cbEfB02062241cf979e4994b656FB944
[consensus.sub.solo]
genesis="0xab7F5238cbEfB02062241cf979e4994b656FB944"
genesisBlockTime=1514533333

[mver.consensus]
fundKeyAddr = "0xab7F5238cbEfB02062241cf979e4994b656FB944"
powLimitBits="0x1f00ffff"
maxTxNumber = 10000     #160

[mver.consensus.ForkChainParamV1]
maxTxNumber = 10000

[mver.consensus.ForkTicketFundAddrV1]
fundKeyAddr = "0xab7F5238cbEfB02062241cf979e4994b656FB944"

[store]
name="kvmvccmavl"
driver="leveldb"
dbPath="datadir/mavltree"
dbCache=128
# store数据库版本
storedbVersion="2.0.0"

[store.sub.mavl]
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneHeight=10000
# 是否使能mavl数据载入内存
enableMemTree=true
# 是否使能mavl叶子节点数据载入内存
enableMemVal=true
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000
tkCloseCacheLen=100000

[store.sub.kvmvccmavl]
# 开启该配置可以方便遍历最新的状态数据，节省磁盘空间可以关闭该配置项
enableMVCCIter=true
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneMavlHeight=10000
# 开启该配置项会精简mvcc历史高度的数据，默认不精简
enableMVCCPrune=false
# 每次精简mvcc的间隔高度，默认每100w高度精简一次
pruneMVCCHeight=1000000
# 是否使能mavl数据载入内存
enableMemTree=true
# 是否使能mavl叶子节点数据载入内存
enableMemVal=true
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000
tkCloseCacheLen=100000
# 该参数针对平行链，主链无需开启此功能
enableEmptyBlockHandle=false

[wallet]
minFee=100000
driver="leveldb"
dbPath="wallet"
dbCache=16
signType="secp256k1"

[wallet.sub.ticket]
minerdisable=false
minerwhitelist=["*"]

[wallet.sub.multisig]
rescanMultisigAddr=false

[exec]
enableStat=false
enableMVCC=false
# alias=["token1:token","token2:token","token3:token"]
# 记录地址相关的交易列表，便于按地址查询交易
disableAddrIndex=false
# 记录每个高度总的手续费消耗量
disableFeeIndex=false
# 开启后会进一步精简localdb，用户查询合约功能会受影响，纯挖矿节点可以开启节省磁盘空间
disableExecLocal=false

[exec.sub.token]
saveTokenTxList=true
tokenApprs = [
    "0xab7F5238cbEfB02062241cf979e4994b656FB944"
]

[exec.sub.cert]
# 是否启用证书验证和签名
enable=false
# 加密文件路径
cryptoPath="authdir/crypto"
# 带证书签名类型，支持"auth_ecdsa", "auth_sm2"
signType="auth_ecdsa"

[exec.sub.relay]
genesis="0xab7F5238cbEfB02062241cf979e4994b656FB944"

[exec.sub.manage]
superManager=["0xab7F5238cbEfB02062241cf979e4994b656FB944"]
#autonomy执行器名字
autonomyExec="autonomy"

[exec.sub.paracross]
nodeGroupFrozenCoins=0
#平行链共识停止后主链等待的高度
paraConsensusStopBlocks=30000
#配置平行链资产跨链交易的高度列表，title省略user.p,不同title使用,分割，不同hit高度使用"."分割，
#不同ignore范围高度使用"-"分割，hit高度在ignore范围内，为平行链自身的高度，不是主链高度
#para.hit.10.50.250, para.ignore.1-100.200-300
paraCrossAssetTxHeightList=[]

[exec.sub.autonomy]
total="16htvcBNSEA7fZhAdLJphDwQRQJaHpyHTp"
useBalance=false

[mver.autonomy]
#最小委员会数量
minBoards=20
#最大委员会数量
maxBoards=40
#公示一周时间，以区块高度计算
publicPeriod=120960
#单张票价
ticketPrice=3000
#重大项目公示金额阈值
largeProjectAmount=1000000
#创建者消耗金额bty
proposalAmount=500
#董事会成员赞成率，以%计，可修改
boardApproveRatio=51
#全体持票人参与率，以%计
pubAttendRatio=75
#全体持票人赞成率，以%计
pubApproveRatio=66
#全体持票人否决率，以%计
pubOpposeRatio=33
#提案开始结束最小周期高度
startEndBlockPeriod=720
#提案高度 结束高度最大周期 100W
propEndBlockPeriod=1000000
#最小董事会赞成率
minBoardApproveRatio=50
#最大董事会赞成率
maxBoardApproveRatio=66
#最小全体持票人否决率
minPubOpposeRatio=33
#最大全体持票人否决率
maxPubOpposeRatio=50
#可以调整，但是可能需要进行范围的限制：参与率最低设置为 50%， 最高设置为 80%，赞成率，最低 50.1%，最高80%
#不能设置太低和太高，太低就容易作弊，太高则有可能很难达到
#最小全体持票人参与率
minPubAttendRatio=50
#最大全体持票人参与率
maxPubAttendRatio=80
#最小全体持票人赞成率
minPubApproveRatio=50
#最大全体持票人赞成率
maxPubApproveRatio=80
#最小公示周期
minPublicPeriod=120960
#最大公示周期
maxPublicPeriod=241920
#最小重大项目阈值(coin)
minLargeProjectAmount=1000000
#最大重大项目阈值(coin)
maxLargeProjectAmount=3000000
#最小提案金(coin)
minProposalAmount=20
#最大提案金(coin)
maxProposalAmount=2000
#每个时期董事会审批最大额度300万
maxBoardPeriodAmount =3000000
#时期为一个月
boardPeriod=518400
#4w高度，大概2天 (未生效)
itemWaitBlockNumber=40000

[exec.sub.evm]
#免交易费模式联盟链允许的最大gas，该配置只对不收取交易费部署方式有效，其他部署方式下该配置不会产生作用
#当前最大为200万
evmGasLimit=1000000000
disableQuickGas = true
#evm内部调试输出，指令级的，默认关闭,0：关闭；1：打开
evmDebugEnable=0
ethMapFromExecutor="coins"
ethMapFromSymbol="Rayaxe"
addressDriver="eth"


[exec.sub.coins]
disableAddrReceiver=true
disableCheckTxAmount=true
friendExecer=["evm"]

# 预编译合约配置管理员
[exec.sub.evm.preCompile]
# 激活合token-erc20 的合约管理地址，必须配置管理员地址
superManager=["0xab7F5238cbEfB02062241cf979e4994b656FB944"]

[metrics]
#是否使能发送metrics数据的发送
enableMetrics=false
#数据保存模式
dataEmitMode="influxdb"

[metrics.sub.influxdb]
#以纳秒为单位的发送间隔
duration=1000000000
url="http://influxdb:8086"
database="chain33metrics"
username=""
password=""
namespace=""

